package encryption

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"errors"
	"io"

	"golang.org/x/crypto/pbkdf2"
)

// EncryptService service for generating keys, encryption and decryption of data
type EncryptService struct {
}

// GenerateDEK generates data encryption key (DEK)
func (*EncryptService) GenerateDEK() ([]byte, error) {
	key := make([]byte, 32) // 256 бит для AES-256
	_, err := rand.Read(key)
	if err != nil {
		return nil, err
	}
	return key, nil
}

// GenerateKEK generates key encryption key (KEK) for DEK
func (*EncryptService) GenerateKEK(password string, salt []byte) []byte {
	return pbkdf2.Key([]byte(password), salt, 10000, 32, sha256.New)
}

func (*EncryptService) newGCM(key []byte) (cipher.AEAD, error) {
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, err
	}
	return cipher.NewGCM(block)
}

// Encrypt encrypts given data bytes with given key using AES with GCM
func (s *EncryptService) Encrypt(data, key []byte) ([]byte, error) {
	gcm, err := s.newGCM(key)
	if err != nil {
		return nil, err
	}

	nonce := make([]byte, gcm.NonceSize())
	if _, err := io.ReadFull(rand.Reader, nonce); err != nil {
		return nil, err
	}

	ciphertext := gcm.Seal(nonce, nonce, data, nil)
	return ciphertext, nil
}

// Decrypt decrypts ciphertext bytes generated by Encrypt method. Should be used the same key
func (s *EncryptService) Decrypt(ciphertext, key []byte) ([]byte, error) {
	gcm, err := s.newGCM(key)
	if err != nil {
		return nil, err
	}

	nonceSize := gcm.NonceSize()
	if len(ciphertext) < nonceSize {
		return nil, errors.New("ciphertext too short")
	}

	nonce, ciphertext := ciphertext[:nonceSize], ciphertext[nonceSize:]

	dek, err := gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, err
	}

	return dek, nil
}

// GenerateSalt generates cryptographic random salt bytes array of given size
func (*EncryptService) GenerateSalt(saltSize int) ([]byte, error) {
	saltBytes := make([]byte, saltSize)
	_, err := rand.Read(saltBytes[:])
	if err != nil {
		return nil, err
	}
	return saltBytes, nil
}

// GenerateRecoveryKey generates recovery key encryption key for DEK
func (*EncryptService) GenerateRecoveryKey() ([]byte, error) {
	key := make([]byte, 32)
	_, err := rand.Read(key)
	if err != nil {
		return nil, err
	}
	return key, nil
}
